# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_product_services.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 780)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 780))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 780))
        MainWindow.setStyleSheet("background-color: whitesmoke;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(370, 690, 250, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(33, 103, 120);\n"
"color:white;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/sample/Images/save64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(31, -9, 951, 661))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 15, -1, 15)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.label_32 = QtWidgets.QLabel(self.frame)
        self.label_32.setMinimumSize(QtCore.QSize(120, 120))
        self.label_32.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border:1px solid black;")
        self.label_32.setText("")
        self.label_32.setPixmap(QtGui.QPixmap(":/sample/hba.jpg"))
        self.label_32.setScaledContents(True)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_18.addWidget(self.label_32)
        spacerItem1 = QtWidgets.QSpacerItem(61, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(130, 28))
        self.pushButton_6.setMaximumSize(QtCore.QSize(130, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(33, 103, 120);\n"
"color:white;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sample/Images/gallery64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_5.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setMinimumSize(QtCore.QSize(130, 28))
        self.pushButton_7.setMaximumSize(QtCore.QSize(130, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(33, 103, 120);\n"
"color:white;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/sample/Images/delete264.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_5.addWidget(self.pushButton_7)
        self.horizontalLayout_18.addLayout(self.verticalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setMinimumSize(QtCore.QSize(11, 30))
        self.label_26.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color:red;")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_3.addWidget(self.label_26)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setMinimumSize(QtCore.QSize(180, 22))
        self.label_4.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 3, -1, 15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setMinimumSize(QtCore.QSize(11, 30))
        self.label_28.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color:red;")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_4.addWidget(self.label_28)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(180, 22))
        self.label_5.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_4.addWidget(self.comboBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 5, -1, 15)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_36 = QtWidgets.QLabel(self.frame)
        self.label_36.setMinimumSize(QtCore.QSize(11, 30))
        self.label_36.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:red;")
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_24.addWidget(self.label_36)
        self.label_41 = QtWidgets.QLabel(self.frame)
        self.label_41.setMinimumSize(QtCore.QSize(180, 22))
        self.label_41.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_24.addWidget(self.label_41)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_13.sizePolicy().hasHeightForWidth())
        self.lineEdit_13.setSizePolicy(sizePolicy)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(250, 30))
        self.lineEdit_13.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_24.addWidget(self.lineEdit_13)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 20, -1, 15)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setMinimumSize(QtCore.QSize(11, 30))
        self.label_35.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:red;")
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_23.addWidget(self.label_35)
        self.label_40 = QtWidgets.QLabel(self.frame)
        self.label_40.setMinimumSize(QtCore.QSize(180, 22))
        self.label_40.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_23.addWidget(self.label_40)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_12.sizePolicy().hasHeightForWidth())
        self.lineEdit_12.setSizePolicy(sizePolicy)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(250, 30))
        self.lineEdit_12.setMaximumSize(QtCore.QSize(600, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_23.addWidget(self.lineEdit_12)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setEnabled(True)
        self.label_29.setMinimumSize(QtCore.QSize(11, 30))
        self.label_29.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color:red;")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_8.addWidget(self.label_29)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setMinimumSize(QtCore.QSize(180, 88))
        self.label_6.setMaximumSize(QtCore.QSize(180, 88))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setMinimumSize(QtCore.QSize(200, 88))
        self.textEdit.setMaximumSize(QtCore.QSize(600, 88))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_8.addWidget(self.textEdit)
        spacerItem5 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setMinimumSize(QtCore.QSize(11, 30))
        self.label_24.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:red;")
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_16.addWidget(self.label_24)
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setMinimumSize(QtCore.QSize(175, 22))
        self.label_21.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_8.sizePolicy().hasHeightForWidth())
        self.lineEdit_8.setSizePolicy(sizePolicy)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_8.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_16.addWidget(self.lineEdit_8)
        spacerItem6 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(389, 34))
        self.label.setMaximumSize(QtCore.QSize(389, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem8 = QtWidgets.QSpacerItem(95, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(389, 34))
        self.label_2.setMaximumSize(QtCore.QSize(389, 34))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setMinimumSize(QtCore.QSize(11, 30))
        self.label_31.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color:red;")
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_19.addWidget(self.label_31)
        self.label_23 = QtWidgets.QLabel(self.frame)
        self.label_23.setMinimumSize(QtCore.QSize(180, 22))
        self.label_23.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_9.setSizePolicy(sizePolicy)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_19.addWidget(self.lineEdit_9)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem9)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 10, -1, 15)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_37 = QtWidgets.QLabel(self.frame)
        self.label_37.setMinimumSize(QtCore.QSize(11, 30))
        self.label_37.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:red;")
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_21.addWidget(self.label_37)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setMinimumSize(QtCore.QSize(180, 22))
        self.label_25.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_11.sizePolicy().hasHeightForWidth())
        self.lineEdit_11.setSizePolicy(sizePolicy)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_11.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_21.addWidget(self.lineEdit_11)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_21)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, -1, -1, 15)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_33 = QtWidgets.QLabel(self.frame)
        self.label_33.setMinimumSize(QtCore.QSize(11, 30))
        self.label_33.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color:red;")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_20.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.frame)
        self.label_34.setMinimumSize(QtCore.QSize(180, 22))
        self.label_34.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_20.addWidget(self.label_34)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setMinimumSize(QtCore.QSize(200, 30))
        self.comboBox_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;\n"
"")
        self.comboBox_4.setEditable(False)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBox_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 10, -1, 15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setMinimumSize(QtCore.QSize(11, 30))
        self.label_27.setMaximumSize(QtCore.QSize(11, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color:red;")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_6.addWidget(self.label_27)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setMinimumSize(QtCore.QSize(180, 22))
        self.label_8.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.spinBox = QtWidgets.QSpinBox(self.frame)
        self.spinBox.setMinimumSize(QtCore.QSize(200, 30))
        self.spinBox.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("border-radius:3px;\n"
"border:1px solid gray;\n"
"background-color:white;\n"
"color:gray;")
        self.spinBox.setMaximum(1000000000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Product / Services"))
        self.pushButton_5.setText(_translate("MainWindow", "Save Product/Service"))
        self.pushButton_6.setText(_translate("MainWindow", "Select"))
        self.pushButton_7.setText(_translate("MainWindow", "Remove"))
        self.label_26.setText(_translate("MainWindow", "*"))
        self.label_4.setText(_translate("MainWindow", "Type :"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Product"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Service"))
        self.label_28.setText(_translate("MainWindow", "*"))
        self.label_5.setText(_translate("MainWindow", "Category :"))
        self.label_41.setText(_translate("MainWindow", "SKU :"))
        self.label_35.setText(_translate("MainWindow", "*"))
        self.label_40.setText(_translate("MainWindow", "Product Name :"))
        self.label_6.setText(_translate("MainWindow", "Description :"))
        self.label_21.setText(_translate("MainWindow", "HSN :"))
        self.label.setText(_translate("MainWindow", "Sales Information"))
        self.label_2.setText(_translate("MainWindow", "Purchase Information"))
        self.label_31.setText(_translate("MainWindow", "*"))
        self.label_23.setText(_translate("MainWindow", "Unit Price (INR) :"))
        self.label_25.setText(_translate("MainWindow", "Purchase Rate (INR) :"))
        self.label_34.setText(_translate("MainWindow", "Tax :"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "1% GST"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3% GST"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "5% GST"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "12% GST"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "18% GST"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "28% GST"))
        self.label_8.setText(_translate("MainWindow", "Quantity :"))

#import add_new_comp_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

